### ISSUE TITLE
Allow upper case acronyms in camel case validator

### ISSUE THREAD

**Issue by croomes** [IBM/openapi-validator#105]
We are using openapi-validator on an api that conforms to the [Kubernetes API conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#naming-conventions).

The `lower_camel_case` validator is close but it doesn't allow acronyms such as `UserID` or `IPAddress` to be capitalised, so this convention fails:

> All letters in the acronym should have the same case, using the appropriate case for the situation. For example, at the beginning of a field name, the acronym should be all lowercase, such as "httpGet". Where used as a constant, all letters should be uppercase, such as "TCP" or "UDP".

This could be solved in a few of ways:

1. Amend regexes for `upper_camel_case` and `lower_camel_case`, but this affects current users who might not want this:
```
diff --git a/src/plugins/utils/caseConventionCheck.js b/src/plugins/utils/caseConventionCheck.js
index 927cabb..b92d087 100644
--- a/src/plugins/utils/caseConventionCheck.js
+++ b/src/plugins/utils/caseConventionCheck.js
@@ -7,8 +7,8 @@
 
 const lowerSnakeCase = /^[a-z][a-z0-9]*(_[a-z0-9]+)*$/;
 const upperSnakeCase = /^[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$/;
-const upperCamelCase = /^[A-Z][a-z0-9]+([A-Z][a-z0-9]+)*$/;
-const lowerCamelCase = /^[a-z][a-z0-9]*([A-Z][a-z0-9]+)*$/;
+const upperCamelCase = /^[A-Z]+[a-z0-9]+([A-Z]+[a-z0-9]*)*$/;
+const lowerCamelCase = /^[a-z][a-z0-9]*([A-Z]+[a-z0-9]*)*$/;
 const lowerDashCase = /^[a-z][a-z0-9]*(-[a-z0-9]+)*$/;
 const upperDashCase = /^[A-Z][A-Z0-9]*(-[A-Z0-9]+)*$/;
```
2. Add additional validators for the less restrictive format, e.g. `upper_camel_case_loose` and `lower_camel_case_loose`.
3. Decide this is too specialized and not something you want to cater for.

I can submit a PR for option 1 or 2 based on preference.

**Comment by dpopp07** [comment]
@croomes Thanks for the issue. I don't want to amend the existing expressions but I think Option 2 sounds good. I think a more descriptive annotation than "loose" might be preferable but I can't think of anything else at the moment so I defer to your opinion there.

It would be great if you could submit a PR!
