### ISSUE TITLE
Multiple scheme security requirement should be allowed

### ISSUE THREAD

**Issue by jormaechea** [IBM/openapi-validator#108]
https://github.com/IBM/openapi-validator/blob/0c0b39c3f83f14f4213afa5eb62a5076d0f1f9d6/src/plugins/validation/2and3/semantic-validators/security-ibm.js#L60-L75

According to the [standard](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#security-requirement-object):
> Security Requirement Objects that contain multiple schemes require that all schemes MUST be satisfied for a request to be authorized. This enables support for scenarios where multiple query parameters or HTTP headers are required to convey security information.

You're checking that each Security Requirement Object contains only one scheme, and setting a _non-configurable warning_.

I suggest one of the following:
a) Remove this validation, because is non-standard.
b) Make it configurable so user can decide what to do with it.

Thanks.

PD: Are you reviewing PRs?

**UPDATE**
This should be also be fixed, because it only labels the first one as _used_.
https://github.com/IBM/openapi-validator/blob/f8cc2bd6411c4450682b6c4c10703f83f2cde19d/src/plugins/validation/2and3/semantic-validators/security-definitions-ibm.js#L77-L78

**Comment by dpopp07** [comment]
@jormaechea Thanks for pointing this out - this does look like a mistake. To answer your question, yes, we are happy to review PRs so feel free to open one!

**Comment by jormaechea** [comment]
@dpopp07 Great! I'll tackle it this week and get back to you!
