### ISSUE TITLE
Request for a higher order error for bad "type"

### ISSUE THREAD

**Issue by jamescooke** [IBM/openapi-validator#117]
Am running v0.15.2 installed inside a Node 13.2.0 alpine Docker container.

Given the following openapi v3 spec:

```yaml
openapi: 3.0.0
info:
  description: Test types
  version: '0'
  title: Thing service serves things
servers:
  - url: 'https://example.com/test'
paths:
  '/thing':
    get:
      summary: Get thing
      operationId: get_thing
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                type: object
                properties:
                  thing:
                    type: thing
```

There is a problem on the last line `type: thing`.

## Current behaviour

When editing this file in the latest Swagger editor at http://editor.swagger.io/ the following error is shown:

![Screenshot from 2019-11-26 12-44-55](https://user-images.githubusercontent.com/781059/69636037-a1205b80-104d-11ea-8d1c-c38c84ac6aa3.png)

And the validator *does* return an error, which is good. This is the error returned:

```
errors

  Message :   Property type+format is not well-defined.
  Path    :   paths./things.get.responses.200.content.application/json.schema.properties.things.type
  Line    :   23
```

There are two problems with this current behaviour of the validator:

1. In this case, `format` has not been defined, so it's a confusing error message. My guess is that there is no value we could add for `format` that would fix this error.

2. The real error which is that the `type` of `thing` is invalid is not being returned, so the validator is not helping the user "get back on track".

## Desired behaviour

Would it be possible to generate a new higher order error? In this case something that matches what the swagger editor returns?

```
errors

  Message :   Property type is not equal to one of the allowed values.
  Path    :   paths./things.get.responses.200.content.application/json.schema.properties.things.type
  Line    :   23
```

I think that would be helpful because it seems to me that the root cause of the problem is that the `type` is not one of the allowed values: "array, boolean, integer, number, object, string", rather than there being an issue with `format`, which is unspecified in this example.

Having a new type error would mean more control available in the config file because `type+format` errors could be tuned down for files that are using custom `format` such as "uuid", without stomping on important `type` errors like this one.

**Comment by dpopp07** [comment]
Having an independent error for an invalid `type` seems like a good idea to me, I will look into this soon!
