### ISSUE TITLE
operationIds validation incorrectly handling sub-resources

### ISSUE THREAD

**Issue by bvanhav** [IBM/openapi-validator#131]
**Issue Type:** bug

**Validator Version:** v0.17.0

**Issue:** When I have a sub-resource in my spec (example path `/resource/{resource-id}/sub-resource`) the validator does not validate the operationId correctly. In this case I would expect a POST /resource/{resource-id}/sub-resource to allow an operationId of `create_resource_sub_resource` (or similar), but the validator raises a warning unless the operationId starts with `update` (which is technically not correct as this is a create of a child-resource).

There is a similar problem with listing sub-resources (validator requires operationId to start with `get` and won't allow `list`).

The following yaml should duplicate the problem:
```
components:
  parameters:
    resource_id:
      description: The resource identifier
      in: path
      name: resource_id
      required: true
      schema:
        type: string
paths:
  /resource/{resource_id}/child_resource:
    post:
      description: Create a child resource.
      operationId: create_resources_child_resource
      parameters:
      - $ref: '#/components/parameters/resource_id'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChildResource'
        description: The child resource template
        required: true
      responses:
        "201":
          description: Created
      summary: Add child resource to a resource
      tags:
      - Child Resource
components:
  schemas:
    ChildResource:
      properties:
        name:
          description: Name of child resource
          type: string
          example: My Child Resource
      required:
      - name
      description: The template for the child resource
      type: object
      title: ChildResource
```

**Comment by dpopp07** [comment]
@bvanhav Thanks for bringing this up, someone on our team will work on it soon.

**Comment by SaltedCaramelCoffee** [comment]
This issue is fixed in https://github.com/IBM/openapi-validator/pull/133, closing.
