### ISSUE TITLE
Invalid regular expression: /^(update[a-zA-Z0-9_]+/: Unterminated group

### ISSUE THREAD

**Issue by Cameron-Kurotori** [IBM/openapi-validator#138]
We are running the openapi linter on our spec with version 0.19.1 and are receiving the following error:
`Invalid regular expression: /^(update[a-zA-Z0-9_]+/: Unterminated group`

https://github.com/IBM/openapi-validator/commit/c44f2fa#diff-803dc7e3acbb8f254a803b9018a83a71R115

May be missing a `)`

**Comment by dpopp07** [comment]
@Cameron-Kurotori Thanks for the issue!

@SaltedCaramelCoffee - will you take a look at this?

**Comment by SaltedCaramelCoffee** [comment]
@dpopp07 The fix for this bug is included in https://github.com/IBM/openapi-validator/pull/137. Can you review and approve it?

**Comment by SaltedCaramelCoffee** [comment]
@Cameron-Kurotori The fix has been released and is part of v0.20.0 of the openapi-validator. Thanks again for reporting it. Please let us know if you found more issues.

**Comment by Cameron-Kurotori** [comment]
Thank you! Much appreciated :)
