### ISSUE TITLE
Configurable operationId naming convention

### ISSUE THREAD

**Issue by fenuks** [IBM/openapi-validator#148]
#124 adds linting naming conventions for `operationId`, but apparently, there is no option to disable it, or change which verbs are in convention, e.g. in my case I would like to use `search` verb instead of `list` when GET endpoint has parameters, since in my API, it's always a search operation.

openapi-validator version: 0.24.0

**Comment by dpopp07** [comment]
@fenuks There should certainly be a way to disable it. If that is not currently implemented, we will fix that.

As for custom verbs, that would require more effort and we may not be able to prioritize that at the moment. We can look into it though.

**Comment by fenuks** [comment]
Thank you, of course it's understandable that custom verbs is not something that is highly needed, especially that current ones work for you.

As for disabling this rule, I believe there is no possibility now, there is no mention in documentation about it, beside that I quickly skimmed through code, and to my understanding, there is no switch to turn checking off.

**Comment by dpopp07** [comment]
I confirmed that you are correct - there is no way to configure this option. This needs to be fixed soon. @barrett-schonefeld @presto21 will one of you take on this issue?
