### ISSUE TITLE
Support extensible async plug-in validations (outside of the code base)

### ISSUE THREAD

**Issue by marklindell** [IBM/openapi-validator#153]
I would like to be able to add my custom rules validations outside of the code base. Right the only option is to add it to the code base and modify the .defaultsForValidator.js  I also need to use async functions from third party libraries in my custom validations (such as the wordpos library). This is not possible without the design supporting async validators.

**Comment by jorge-ibm** [comment]
@marklindell - we've recently integrated Spectral into our validator. Does this new integration meet your needs ?

**Comment by dpopp07** [comment]
@marklindell Specifically, Spectral allows you to define your own rules and your own functions. These Spectral-formatted rules can now be used with our validator. [Here is some documentation](https://meta.stoplight.io/docs/spectral/docs/guides/5-custom-functions.md#async-functions) for adding custom async functions with Spectral. We will have more documentation around the integration soon

**Comment by mkistler** [comment]
I've updated our docs with information about how to add custom validations.  I believe this fully addresses your requirement.  If not, feel free to open a new issue describing what is missing.
