### ISSUE TITLE
Unable to set default value to null

### ISSUE THREAD

**Issue by gamezfreak** [IBM/openapi-validator#155]
Hi,

First off, I love the linting capabilities of this project, it is so much more valuable than just straight spec validation to ensure consistent API conventions and encourage strong documentation within the spec.

My project uses null values to indicate a property has never been configured and many properties default to null if not set.

When I run validation on my schema file I'm getting errors like:
>  Message :   Null values are not allowed for any property.
>  Path    :   components.schemas.ConnectId.properties.profile_picture.default
>  Line    :   234

That property is defined in my schema as
> profile_picture:
>   type: string
>   nullable: true
>   default: null
>   description: "A base64 encoded image string for the user's avatar"

I went looking for a linter option to change the behavior and found null values are just globally considered errors and there is no option to allow null as a default value.  See https://github.com/IBM/openapi-validator/blob/master/src/plugins/validation/2and3/semantic-validators/walker-ibm.js#L51

Based on this clarification of the `nullable` keyword in OAS 3.0.3 I believe my use case is valid.
https://github.com/OAI/OpenAPI-Specification/blob/master/proposals/003_Clarify-Nullable.md#is-null-allowed-as-the-default-value-of-a-nullable-schema-see-2057

**Comment by dpopp07** [comment]
Glad you are enjoying this tool! Looking at the spec, you are indeed correct and we should support that use case. I will look into it soon. Thanks for reporting!

**Comment by mkistler** [comment]
I think simply omitting `default` is equivalent to `default: null`. Is there some reason this isn't sufficient?

**Comment by gamezfreak** [comment]
@mkistler I tried removing the `default: null` parameter but that also causes "default: null" to be removed from the documentation I am generating with redoc.  I'd prefer that to be explicit in my documentation that it will be null and not an empty string when unspecified.  Maybe that is an issue there as well in their project, but I think the OAS 3.0.3 clarification on nullable would still allow `default: null`.  I'm trying to use null vs "" to be forward-thinking around data migrations; did the user set an empty value vs never set any value.

**Comment by sirosen** [comment]
To offer another motivating use-case for this: I'm generating an openapi spec from my schemas, and `default: null` is the output from my spec generation tool. So even if I wanted to remove `default: null`, it's difficult to do so in this case.

It would be nice to be able to disable this check altogether as a workaround, but I don't think that's supported by the config options.
