### ISSUE TITLE
Please provide a property to retrieve validated document model

### ISSUE THREAD

**Issue by Klaus-Nji-sp** [IBM/openapi-validator#158]
The output of the validator only returns errors and warnings but does not return the document model.  This could be particularly useful if the document had external references which needed to be resolved.

Would it be possible to expose a property which returns the final and possibly exploded validated document model?

**Comment by dpopp07** [comment]
I'm not sure I quite understand what you're asking for here. What do you mean by document model?

**Comment by Klaus-Nji-sp** [comment]
A file containing the OpenAPI spec was read and its references were resolved for validation to have been performed I am suspecting.  This is the document model I am referring to.  As a consume of this API can I get a hold of this model?  

Use case is:  I have run a spec through your validator.   I will like to see how the external references were resolved and what the final output looks like.  It will be nice to not have to call another library or API to load the spec and resolve reference.  https://www.npmjs.com/package/openapi-enforcer  does this.

**Comment by dpopp07** [comment]
Okay, I understand. This feature can be added. Are you using this tool on the command line or as a Node module?

If on the command line, would you want the result written to a new file?

**Comment by Klaus-Nji-sp** [comment]
In a Node module.

**Comment by dpopp07** [comment]
Great. That certainly makes sense to add. I will try to do that soon

**Comment by Klaus-Nji-sp** [comment]
Muchly appreciated. Thank you.

**Comment by jorge-ibm** [comment]
@Klaus-Nji-sp are you still needing this feature ?

**Comment by dpopp07** [comment]
Closing as stale
