### ISSUE TITLE
Bug: A path parameter under root node AND under the method node leads to crash / internal error

### ISSUE THREAD

**Issue by nrail-joerg-walter** [IBM/openapi-validator#166]
Code:

`  /xs/{xId}:
    parameters:
      - $ref: '#/components/parameters/xIdParameter'
    patch:
      description:
        Updates an x.
      summary: Update x {xId}
      tags:
        - xs
      parameters:
        - $ref: '#/components/parameters/xIdParameter'
      operationId: updatex
      x-eov-operation-handler: routes/xs
      responses:
        200:
          description: Successful response
        401:
          description: Unauthorized request
    delete:
      description:
        Deletes x {xId}
      summary: Delete x {xId}
      tags:
        - xs
      security: 
        - BearerJwtSchema: []
      operationId: deletex
      x-eov-operation-handler: routes/xs
      responses:
        200:
          description: Successful response
        401:
          description: Unauthorized request`

leads to 

`[Error] There was a problem with a validator.
Cannot read property 'findIndex' of undefined`

**Comment by dpopp07** [comment]
Thanks for the issue. I'm going to look into this ASAP

**Comment by dpopp07** [comment]
Resolved with #168
