### ISSUE TITLE
Add option in .validaterc to override unused definition warning

### ISSUE THREAD

**Issue by georgekamel** [IBM/openapi-validator#172]
I notice that there is no option in .validaterc to override the warning: "Definition was declared but never used in document". Is there any chance this could be added as an option?

**Comment by dpopp07** [comment]
You're right about that. This is a fairly minor warning so I agree it should be configurable.

Is there any way you could open a PR for this? If not, I should be able to get to it within a couple of week.

**Comment by mkistler** [comment]
This is a check that is inherited from the open-source code we used as a base for the validator, and none of those checks were configurable.  But I agree that it would be nice to be able to turn this off, so we'd welcome a PR for this.

**Comment by jorge-ibm** [comment]
We should investigate if spectral has a rule for this.

**Comment by dpopp07** [comment]
This is now supported through the Spectral rule `oas3-unused-component`
