### ISSUE TITLE
Objects with a property named "security" throw errors complaining that "security requirements must match a security definition"

### ISSUE THREAD

**Issue by krisolafson** [IBM/openapi-validator#18]
I believe this validation check should only be done when "security" is at the resource level.

**Comment by krisolafson** [comment]
Sure, I tried to strip down an example that was throwing some errors for us

`openapi: 3.0.0
info:
    title: Cloud API
    description: The Customer Experience Engineering (CXE) OpenAPI specification.
    version: 2.0.0
    contact:
        name: Customer Experience Engineering (CXE)
        url: 'https://backlog.acquia.com/secure/CreateIssue!default.jspa?pid=16580'
        email: cx-eng@acquia.com
servers:
    -
        url: 'https://cloud.acquia.com/api'
        description: Cloud API
components:
    schemas:
        Insight:
            type: object
            required:
                - uuid
                - label
                - hostname
                - status
                - updated_at
                - last_connected_at
                - scores
                - counts
                - flags
                - _links
            description: Insight response object.
            properties:
                uuid:
                    type: string
                    format: uuid
                    description: The site UUID.
                label:
                    type: string
                    description: The site label.
                hostname:
                    type: string
                    format: uri
                    description: The site uri.
                status:
                    type: string
                    description: The site status.
                updated_at:
                    type: string
                    format: date-time
                    description: Last updated time.
                last_connected_at:
                    type: string
                    format: date-time
                    description: Last connected time.
                counts:
                    type: object
                    description: Site scores counts.
                    properties:
                        best_practices:
                            $ref: '#/components/schemas/InsightScoreCounts'
                        performance:
                            $ref: '#/components/schemas/InsightScoreCounts'
                        security:
                            $ref: '#/components/schemas/InsightScoreCounts'
        InsightScoreCounts:
            type: object
            required:
                - pass
                - fail
                - ignored
                - total
                - percent
            properties:
                pass:
                    type: integer
                    description: The number of passing tests.
                fail:
                    type: integer
                    description: The number of failing tests.
                ignored:
                    type: integer
                    description: The number of ignored tests.
                total:
                    type: integer
                    description: The number of total tests.
                percent:
                    type: integer
                    description: The percentage of passing tests.
    securitySchemes:
        OAuth2:
            type: oauth2
            flows:
                clientCredentials:
                    authorizationUrl: 'https://accounts.acquia.com/api/authorize'
                    tokenUrl: 'https://accounts.acquia.com/api/token'
                    scopes: {}
paths:
    '/insight/{site_id}':
        get:
            tags:
                - Insight
            summary: Returns insight data for a particular site.
            operationId: findInsightDataBySiteId
            security:
                -
                    OAuth2: []
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Insight'
`

**Comment by dpopp07** [comment]
@krisolafson Thanks for posting that - this is a bug and I've identified the problem. The fix will be released early next week, likely on Monday.

**Comment by krisolafson** [comment]
Works like a charm, thank you very much!
