### ISSUE TITLE
Additional Configurability

### ISSUE THREAD

**Issue by ccampanale** [IBM/openapi-validator#208]
First, thanks for maintaining this useful package!

I'm currently testing the use of this package as a library dependency in package that itself will be a dependency for several packages in a project I maintain. The only way I see to customize the configuration for the validator is by means of the `.validaterc` file which is unfortunately less than ideal for my use case.

I would like to override the validation configuration from the package which I am implementing the use of this library with the option for dependents to additionally customize the configuration. For dependents - which will ultimately be the point of entry at runtime - maintaining a custom `.validaterc` in the package should work fine. However, this does not seem to work well from the dependency's perspective. (Unless I've done something wrong, the configuration file maintained in my dependency package is not recognized when used from a dependent in my testing.)

One option would be exposing the `configFileOverride` param in the signature for `Config.getConfigObject` in the API such that the a specific path could be provided. I would imagine then that this path could be provided and resolve to the file buried within the `node_modules` directory.

Another option would be allowing for `defaultMode` in the same function to be of type `boolean | typeof configFile | undefined` allowing for the current functionality as well as additionally providing a config object programmatically. With this option exposed, dependents using your package as a library could generate a configuration file and provide it to the validator upon use.

I personally lean in favor of the second approach which, in my opinion, adds better support for programmatic use of this package which favors use as a CLI currently.

Thoughts? Questions?

**Comment by dpopp07** [comment]
Hey @ccampanale thanks for the issue. I agree, this use case isn't handled well at the moment and I like the idea of adding a way of programmatically specifying the config. I think there will be some additional caveats I'll need to consider and discuss with the team but I'll try and get back to you soon on this!

**Comment by ccampanale** [comment]
Fantastic, @dpopp07 thanks for the response!
If you get an idea of the direction the team wants to go but don't have the cycles to implement, definitely let me know here. I might be able to get a PR started.

**Comment by hpl002** [comment]
+1

Would be great to have at least some of the [options that the CLI offers](https://github.com/IBM/openapi-validator#options) available in the node module. 
E.g.,
- Specify path to .validaterc
- Specify path to ruleset
- Get statistics, as opposed to the results object
- Get errors only

So far **very** impressed with how customizable and extensible the validator is

**Comment by dpopp07** [comment]
I will look at this issue this week

cc @ccampanale 
@hpl002 Glad you are enjoying the tool thus far

**Comment by dpopp07** [comment]
We've overhauled how configuration works in this tool so I'm not sure how relevant this is anymore. Feel free to re-open if you want to have more discussion
