### ISSUE TITLE
CLI does not dereference $refs

### ISSUE THREAD

**Issue by hpl002** [IBM/openapi-validator#229]
Perhaps this is by design, but i feel as this might deserve a mention in the readme.

Was scratching my head trying to figure out why the CLI and node module were turning out different statistics, the $refs being the culprit.

Provided that the node module expects a parsed object then it is up to the client to decide if the document should be dereferenced or not. Given that the CLI takes the file directly, then the dereferencing responsibility is (arguably) moved onto the CLI and its internal parser.

OR

Simply mention in the readme that the CLI will not dereference. Could perhaps be added as a option?

My two cents,

Herman

**Comment by jorge-ibm** [comment]
@dpopp07

**Comment by dpopp07** [comment]
@hpl002 I'm not sure what you mean so may need some more info.

The CLI validator does resolve references. What behavior are you seeing that indicates otherwise?

If the output from CLI and node module are different, there may be a bug for us to address. In that case, will you send the discrepancy you are seeing in the output?

Or even better, if you can link us to your OpenAPI document, we can try to reproduce on our end.

**Comment by hpl002** [comment]
Create a tiny working example: https://github.com/hpl002/issue-ibm-openapi-validator

**Comment by dpopp07** [comment]
Thanks for putting that together, I will check it out.

**Comment by hpl002** [comment]
any updated on this?

**Comment by dpopp07** [comment]
Was not able to look at it yesterday, planning on looking today

**Comment by dpopp07** [comment]
@hpl002 Okay I know what is going on. There are two main factors at play in your diff:

1. The CLI dereferences the spec just fine but it _also_ keeps the unresolved spec and performs validation on both. When you dereference the spec in your own code, before calling the validator, you lose the original information. That is why when you run the tool on the already resolved spec, you get warnings like
> Response schemas should be defined with a named ref.

The tool looks for `$ref` fields in the original spec and does other processing on the fully resolved spec.

2. There is a file that is looking at only the original (unresolved) spec and performing validations. This was written with only one file in mind - using a multi-file spec leads to missed validations. This is the explanation for the warning:
> Schema properties must have a description with content in it.
which was present when validating the already resolved spec.

This is a bug on our part, so I will make a note to fix it.

Just to let you know, my results were different than what you detailed in your `index.js` file. I got 7 warnings for the original spec and 13 warnings for the fully resolved spec. I am guessing that the 6 extra were the same as your 6 extra (consisting of the two messages above) but if not, let me know so I can see if there are other bugs.

I will also say, for clarity, _both_ the CLI and node module will always dereference the spec and process the original spec alongside the resolved spec. There should not be a need to resolve the spec yourself in either case.
