### ISSUE TITLE
no_response_body exclusion for OPTIONS requests

### ISSUE THREAD

**Issue by timtucker** [IBM/openapi-validator#235]
General convention for OPTIONS requests is to return an empty 200 response with Content-Length=0.

Doing some investigation, some builds of FireFox even flag preflight requests that return anything other than 200 as an error (not sure on the behavior for the current release).

The no_response_body rule should either ignore empty response bodies for OPTIONS requests or allow configuration to exclude them.

**Comment by dpopp07** [comment]
Looking into it, it seems like it's a common enough pattern to disable this rule for OPTIONS requests. I think I prefer that to allowing general configuration for turning this rule off. @mkistler @hudlow any opinions here?

If we agree that's the best way forward, @timtucker would you be willing to open a PR for that change? If not, I will try to get to it soon.

**Comment by mkistler** [comment]
Skipping that check for `OPTIONS` sounds very reasonable to me.  I don't think a configuration setting is needed.
