### ISSUE TITLE
Any way to suppress specific errors/warnings without completely disabling a rule?

### ISSUE THREAD

**Issue by Ziaunys** [IBM/openapi-validator#294]
I have an existing spec which has some violations of rules that I would actually like to keep enabled to prevent further violations, but I'd like to ignore the existing ones. Is this currently possible?

**Comment by dpopp07** [comment]
@Ziaunys Unfortunately, I do not believe that is possible at this time.

**Comment by Grahahax** [comment]
Partially disabling rules would be very useful for us too, we also have an existing spec which we'd like to follow best practice for new additions, but disable just the existing parts we can't or don't want to follow a rule for.

Other linters often use inline annotation which obviously wouldn't be appropriate here, but I think a way to configure exclusions via paths would work well.

Examples of eslint:
https://eslint.org/docs/user-guide/configuring/rules#disabling-rules

**Comment by Grahahax** [comment]
@dpopp07 I'm not familiar with the structure of this repo so I've quickly created a draft for feedback before I spend too much time testing. How does this approach look to you, any other idea?

**Comment by dpopp07** [comment]
This is now possible with [Spectral overrides](https://meta.stoplight.io/docs/spectral/ZG9jOjI1MTg5-custom-rulesets#overrides). Only rules defined in our `@ibm-cloud/openapi-ruleset` ruleset are supported but we are currently in the process of converting all of our existing rules to this format.
