### ISSUE TITLE
ibm-openapi-validator upgrade to 0.46.0 not recognising 'parameters' in .validaterc as a valid category

### ISSUE THREAD

**Issue by ewillis91** [IBM/openapi-validator#295]
Error:  Invalid configuration in .validaterc file. See below for details.

 - 'parameters' is not a valid category.
   Valid categories are: operations, responses, schemas

**Comment by rhymes** [comment]
Re-running `lint-openapi init` worked for me, or removing the fields removed in this PR https://github.com/IBM/openapi-validator/pull/286

**Comment by dpopp07** [comment]
@ewillis91  - there were changes that require an update of the .validaterc file and @rhymes is correct, those are the solutions (thanks for commenting).

Unfortunately, we forgot to use our deprecation mechanism we have in the code to remove rules without errors like these. So while the file needs to be manually updated right now, this shouldn't happen again moving forward.

**Comment by meem** [comment]
I'm also seeing this problem, in addition to the following errors:

```
 - 'no_request_body_content' is not a valid rule for the operations category
   Valid rules are: no_request_body_name
 - 'no_response_codes' is not a valid rule for the responses category
   Valid rules are: no_success_response_codes, protocol_switching_and_success_code, no_response_body, ibm_status_code_guidelines
```

What are the new ways these rules are expressed?

Attn: @hudlow

**Comment by barrett-schonefeld** [comment]
@meem to resolve this problem, you can remove the offending rules (`no_request_body_content` and `no_response_codes`) from `.validaterc`.

**Comment by meem** [comment]
@barrett-schonefeld Thanks!  Does `oa3s-schema` also cover  these `oas3.parameters` checks?
```
    "parameters": {
      "no_in_property": "error",
      "invalid_in_property": "error",
      "missing_schema_or_content": "error",
      "has_schema_and_content": "error"
    },
```

**Comment by barrett-schonefeld** [comment]
@meem Yes, that's right!

`has_schema_and_content` is covered by the Spectral rule `parameter-schema-or-content`.

**Comment by dpopp07** [comment]
Use of the `.validaterc` file is now deprecated. See [the new documentation around customization](https://github.com/IBM/openapi-validator/blob/main/docs/ibm-cloud-rules.md#customization) for more info.
