### ISSUE TITLE
"non-204 responses should define a content object" seems too narrow

### ISSUE THREAD

**Issue by meem** [IBM/openapi-validator#298]
Our API has two cases which seem like legitimate exceptions to the "non-204 responses should define a content object" rule:

- Methods that transition to a WebSocket via a `101 Switching Protocols` response.  Per https://datatracker.ietf.org/doc/html/rfc7231#section-6.2.2 there's no applicable content type in this case.
- Methods that use `202 Accepted`.  While https://datatracker.ietf.org/doc/html/rfc7231#section-6.3.3 advises a status monitor, we do not have one at present (note that we generally use `202` for `DELETE` methods, and thus a subsequent `GET` reveals whether the operation has completed).

In general, this rule is helpful, and did catch some legitimate mistakes in the API specification.  As such, I'd prefer not to simply disable it.

**Comment by dpopp07** [comment]
@meem thanks for the issue. We could probably make exceptions for other reasonable cases. @hudlow any thoughts on this?

**Comment by meem** [comment]
@dpopp07 Thanks!  FWIW I briefly discussed this issue with @hudlow before filing it, and he seemed to concur with these two cases. There may be other response codes worthy of exceptions, but they did not come up in the VPC API.

**Comment by dpopp07** [comment]
Oh okay, great. Sounds good to me. Would you be open to submitting a PR for this? I can try to get to it but it may not be until next month (post Q2).

**Comment by meem** [comment]
@dpopp07 I can try to take a shot at it.  Looking more deeply, it seems there was an older version of this rule (introduced in the semantic validator plugin via commit 90689c89 back in February of 2020) which we'd disabled via `"no_response_body": "off"` in our `.validaterc`.  The new version of this rule was then added to spectral via commit fd347170 in March 2021, but is considered its own rule. 

Is the old rule being deprecated in favor of the new one, or would we want to loosen the checks on both?
I'm also hoping @hudlow can shed some light on why he chose to disable the older version of this rule rather than request the rule itself be broadened.

**Comment by dpopp07** [comment]
@meem Sorry for the delay on this but to answer your question, I believe the old rule will eventually be deprecated in favor of the new one (if it hasn't already).

**Comment by meem** [comment]
@dpopp07 OK, thanks for addressing this with #320 👍
