### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'get')

### ISSUE THREAD

**Issue by Legion112** [IBM/openapi-validator#326]
Another issue with OpenApi as [here](https://github.com/IBM/openapi-validator/issues/319).

Need to make the error more clear to be able to find the place that course the error. 

![image](https://user-images.githubusercontent.com/20613430/134145220-185a585a-b47b-4f74-b917-d249dd45fa94.png)

 I'll send you @dpopp07  the specification and docker run command to email to easily reproduce the error.

**Comment by dpopp07** [comment]
@Legion112 I will look into it but wanted to check something real quick - I see that you are using `jamescooke/openapi-validator`, which is [a fork of this repo](https://github.com/jamescooke/openapi-validator). Just letting you know in case you meant to be interacting with that repo, since there have been a lot of commits here since the fork was created

**Comment by Legion112** [comment]
Oh.. I thought it was the official imagine.  My bad.

**Comment by Legion112** [comment]
@dpopp07  in the documentation [here](https://github.com/IBM/openapi-validator#docker-container) I see `jamescooke/openapi-validator` image. Maybe documentation is wrong or something?

**Comment by dpopp07** [comment]
@Legion112 That is my mistake - I got the Docker image mixed up with the fork of the same name. We don't have an "official" Docker image per se, but that community-supported image is the best one to use and it seems up to date with the latest from this repository.

Sorry for the  misunderstanding, I will look at this issue today.

**Comment by dpopp07** [comment]
@Legion112 I was able to reproduce the issue, looking into a fix now

**Comment by Legion112** [comment]
Any progress on this one?

**Comment by dpopp07** [comment]
@Legion112 Yes, I found the root of the issue on Friday and should be posting a PR today with the fix.

**Comment by dpopp07** [comment]
@Legion112 PR opened here - #333
