### ISSUE TITLE
text/plain body and "request-body-object" rule

### ISSUE THREAD

**Issue by rolivares** [IBM/openapi-validator#344]
I've written an endpoint and the body looks like: 

```
        "requestBody": {
          "content": {
            "text/plain": {
              "schema": {
                "$ref": "#/components/schemas/ApplierRequestStatus"
              }
            }
          },
          "description": "Nuevo valor para el estado de la solicitud"
        },
```

ApplierRequestStatus is defined as a string enumeration like this:

```
      "ApplierRequestStatus": {
        "type": "string",
        "description": "Categorización del estado de una Solicitud en base al estado de procesamiento y de su registro en el sistema",
        "enum": [
          "Draft",
          "Sent",
          "Returned",
          "Finished"
        ],
        "x-examples": {}
      },
```

But linting is advising that "All request bodies MUST be structured as an object" even the content is defined as text/plain. 

```
  Message :   All request bodies MUST be structured as an object
  Rule    :   request-body-object
  Path    :   paths./requests/{uuid}/status.put.requestBody.content.text/plain.schema.type
  Line    :   759
  Component Path    :   components.schemas.ApplierRequestStatus.type
  Component Line    :   3246
```

**Comment by dpopp07** [comment]
Hi @rolivares

This rule comes from our internal API design requirements at IBM, which say
> APIs MUST support JSON by default for sending and receiving data in request and response bodies. Other formats SHOULD NOT be supported except to meet a compelling industry-specific need.

This tool is designed around our API design guidelines but it is configurable if your API does not need to follow this requirement. You can disable the rule entirely - see [this documentation](https://github.com/IBM/openapi-validator/tree/main#changing-spectral-rule-severity) for more info

**Comment by rolivares** [comment]
oh! I see, my mistake ;) thanks
