### ISSUE TITLE
Remove coverage information from deployed package

### ISSUE THREAD

**Issue by Havunen** [IBM/openapi-validator#378]
ibm-cloud / open-api-ruleset includes code coverage data in published package, please remove it to reduce package size:
![image](https://user-images.githubusercontent.com/2021355/154694701-36b42df6-6df9-49c4-aefa-ae66e4ca9432.png)

**Comment by dpopp07** [comment]
Good catch! Thanks for the issue, I'll have this fixed soon

**Comment by dpopp07** [comment]
Should be resolved with #386
