### ISSUE TITLE
Add explicit control of case convention for paths and schema

### ISSUE THREAD

**Issue by aspear** [IBM/openapi-validator#40]
Hi!  This tool is awesome, and  it would be really nice to have explicit control over case conventions for paths, and then schema objects and enums.  As it is, the only control over this is the global boolean "snake_case_only" which is only useful for one convention (presumably IBMs).  In my company (VMware) we have many APIs that come from different products that all have their own ways of handing paths for example, one lower_camel_case, another lower_snake_case.

I propose (and have already implemented!) a couple of small backwards compatible additions:
1) in the paths section, add a new config option "paths_case_convention" that allows explict control.  The .defaultsForValidator.js changes to:
'paths': {
      'missing_path_parameter': 'error',
      'snake_case_only': 'warning',
      'paths_case_convention': ['off', 'lower_snake_case']
    },
The idea here is that a user could set snake_case_only to off, and then use paths_case_convention in a similar manner to the existing param_name_case_convention to explicitly control the selection for paths.

2) Add two additional options in the spirit of the change above for the schemas section:
'schemas': {
     ...
      'property_case_convention': [ 'off', 'lower_snake_case'],
      'enum_case_convention': [ 'off', 'lower_snake_case']
    },
This allows you to have one convention for properties of objects (e.g. lower_snake_case), and then a separate convention for enums (e.g. upper_snake_case, 'MY_ENUM_VALUE')

This  fixes #38 btw.

3) Add additional case convention values upper_snake_case and upper_dash_case (note that my company uses upper_snake_case for enums.  We don't use upper_dash_case, but while I was touching the code I figured I might as well add it so that all cases were covered)

I already have this implemented in a fork.  I am implementing tests right now.  I would be very happy to submit a pull request for it if you are open.

thanks,
Aaron Spear, VMware

**Comment by dpopp07** [comment]
@aspear Thanks for the issue, so glad you like the tool! Making all of the current case convention validations configurable is something we really want to do and it's been sitting in our backlog for a while - we just haven't gotten around to it. We definitely welcome that PR, I will review it soon
