### ISSUE TITLE
Add optional reporting of results in json to allow scripting the tool

### ISSUE THREAD

**Issue by aspear** [IBM/openapi-validator#43]
Adding a new option to the command line tool that allows printing the results directly in json would be nice for use cases where someone wants to script calling lint-open api from another tool.  Something like "lint-openapi --json ./path/to/swagger.json"

I have this implemented already and will submit a PR for it.

**Comment by dpopp07** [comment]
Love this idea. Just this morning, I was just watching a demo of another CLI tool that did this and I noted that we should put it in here at some point. Thanks for these contributions!
