### ISSUE TITLE
print RuleSet version

### ISSUE THREAD

**Issue by michelecurioni** [IBM/openapi-validator#498]
Hi,
would it be possible to print the version of the ruleset package included in the validator?
For instance, when I run 'lint-openapi --version', it would be useful to have something like this:
ValidatorVersion:"0.95.0", RuleSetVersion:"0.44.0"

The format is not important for me, just the information.

The version of the RuleSet package is useful to look at RuleSet's changelog to identify which rule has been modified in that particular version.

Thanks

**Comment by dpopp07** [comment]
@michelecurioni Thanks for the suggestion. That seems very reasonable/useful to me. I'll look at adding that soon
