### ISSUE TITLE
Performance regression on node 16 and 18

### ISSUE THREAD

**Issue by rparini-intellegens** [IBM/openapi-validator#509]
Running the openapi-validator version 0.96.0 for our schema takes ~10s on node 14 but ~7mins on node 16 and 18. This might be a recurrence of https://github.com/IBM/openapi-validator/issues/347 ?

**Comment by dpopp07** [comment]
@rparini-intellegens thanks for the issue. I think this is probably separate from 347 but it is a known problem we are working on resolving. Unfortunately, our initial investigation has yielded some really strange results and we're having trouble identifying the source of the poor performance.

As a temporary workaround while we work on this, we've started including platform-specific binaries with our [release assets](https://github.com/IBM/openapi-validator/releases) that run with vastly improved performance.

**Comment by dpopp07** [comment]
Edit: [this PR](https://github.com/IBM/openapi-validator/pull/508#pullrequestreview-1140834730) shows really promising results for me
