### ISSUE TITLE
Validator dependency not declared

### ISSUE THREAD

**Issue by erezarnon** [IBM/openapi-validator#528]
When running `lint-openai` with `yarn pnp`, you get the following error

```
Error: @ibm-cloud/openapi-ruleset tried to access validator, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

Looks like `openapi-ruleset/src/functions/security-scheme-attributes.js` imports `validator`, but the `validator` package isn't declared as a dependency of the `ruleset` package.

**Comment by dpopp07** [comment]
Great catch! Will be resolved in #529
