### ISSUE TITLE
collections missing from the openapi-ruleset in version 0.45.3

### ISSUE THREAD

**Issue by hideintheclouds** [IBM/openapi-validator#536]
According to the documentation, when defining a custom rule (e.g. overwriting the camelcase convention check), one should use a js snippet like the following:

https://github.com/IBM/openapi-validator/blob/main/docs/ibm-cloud-rules.md#replace-a-rule-from-ibm-cloudopenapi-ruleset

Inside the example, there is a const which is loading the collections:

const { schemas } = require('@ibm-cloud/openapi-ruleset/src/collections');

The problem is that starting with v.0.45.3 of openapi-ruleset, this folder was removed.

https://www.npmjs.com/package/@ibm-cloud/openapi-ruleset?activeTab=explore
https://www.npmjs.com/package/@ibm-cloud/openapi-ruleset/v/0.45.2?activeTab=explore

Note: the collections was probably moved here:
https://www.npmjs.com/package/@ibm-cloud/openapi-ruleset-utilities
https://github.com/IBM/openapi-validator/blob/main/packages/utilities/src/collections/index.js

With the current documentation and the example, the validation will fail, thus resorting to the default IBM validation ruleset.

The documentation needs to be updated accordingly.
Example:
https://github.com/IBM/openapi-validator/blob/main/docs/ibm-cloud-rules.md#replace-a-rule-from-ibm-cloudopenapi-ruleset

`const { schemas } = require('@ibm-cloud/openapi-ruleset/src/collections');`

should become

`const { schemas } = require('@ibm-cloud/openapi-ruleset-utilities/src/collections');`

**Comment by dpopp07** [comment]
Great catch - you are correct. We will get that updated shortly
