### ISSUE TITLE
Outdated info in ruleset doc

### ISSUE THREAD

**Issue by eiri** [IBM/openapi-validator#540]
In the latest refactoring `collections` went into `@ibm-cloud/openapi-ruleset-utilities` package, however [custom rules section](https://github.com/IBM/openapi-validator/blob/main/docs/ibm-cloud-rules.md#replace-a-rule-from-ibm-cloudopenapi-ruleset) in the ruleset doc still has an old export that might be confusing for new users.

**Comment by dpopp07** [comment]
Good catch, thanks Eric! I'll fix that shortly
