### ISSUE TITLE
Problem finding configuration file passed in explicitly

### ISSUE THREAD

**Issue by aspear** [IBM/openapi-validator#55]
It appears that the implementation of findUp that is used to find/validate the configuration file cannot be passed path information as a part of the file name.  Doing so results in redudantly prepending the path to the returned file path.  As a result the --config option does not work as implemented unless the path passed in only has a file name and is located in the current directory.

PR with fix coming.

**Comment by dpopp07** [comment]
Hmm that's interesting, I thought I tested that out properly before I suggested it. What's an example of a filename that would break it?

**Comment by aspear** [comment]
If you pass in only a filename to --config and that file happens to exist in the current working directory or above it, it will work.  If you pass a full path in a different tree, you see the issue.  e.g. 

aspear@aspear-ubuntu:~/oss/openapi-validator
$ node ./src/cli-validator --json --config /home/aspear/repos/rest-api-standards-tool/docs/my-config.json /home/aspear/repos/rest-api-standards-tool/docs/api-validator-openapi-2x.yml

**Comment by dpopp07** [comment]
Oh I see it now, that's bizarre. I guess I forgot to try out an absolute path. That's my my mistake! Thanks for catching it

**Comment by aspear** [comment]
Bah @dpopp07 don't merge this yet, I messed up the commit.

**Comment by aspear** [comment]
OK, the PR is fixed now.  somehow when I was cleaning/linting the change I managed to miss a line.
