### ISSUE TITLE
Update documentation to reflect latest recommendations

### ISSUE THREAD

**Issue by dustinmoris** [IBM/openapi-validator#649]
Hello, first of all thanks for open sourcing this project!

As I was searching through some older issues I came across [this recommendation](https://github.com/IBM/openapi-validator/issues/514#issuecomment-1332714100):

> Our recommendation moving forward is to use [Spectral's Node API](https://meta.stoplight.io/docs/spectral/eb68e7afd463e-spectral-in-java-script) and import our ruleset as a dependency to get consistent behavior with the CLI tool. That's what the CLI tool is doing behind the scenes.

To be honest this is the first time I have heard about Spectral and therefore it was not immediately clear to me how to hook this API validation ruleset up with the Spectral NPM package. I was wondering if you could provide a simple update to the current README to reflect your latest recommendation.

Many thanks :)

**Comment by dpopp07** [comment]
Hello @dustinmoris - I'm glad the project looks beneficial to you!

That's a good suggestion. We'll look at adding that in the docs. In the meantime, we do have a [quick guide in our README for the ruleset package itself](https://github.com/IBM/openapi-validator/tree/main/packages/ruleset). The way to hook it up is to install our ruleset (which is a standalone package), install Spectral separately, and write a Node program to utilize them together as in the linked example.
